#!/usr/bin/env bash

declare file="1.txt"
declare tmp_file="temp.txt"

# validation
declare -a todo_commands=("add" "remove" "show")

command_in_list() {
    local input_command=$1

    for i in "${todo_commands[@]}"; do
        if [[ "$i" == "$input_command" ]]; then
            return 0
        fi
    done
    return 1
}

if command_in_list "$1"; then
    declare user_command=$1
    echo "Command exists: $1"
else
    echo "[ERROR] Commands does not exist: $1"
fi

# logic
rewrite_lines() {
    local id_or_task="$1"
    mapfile -t lines <"$file"
    touch "$tmp_file"

    case "$user_command" in
    add)
        i=1
        for line in "${lines[@]}"; do
            # Remove everything before the first dot and the dot itself
            clean_line="${line#*.}"
            clean_line="${clean_line#"${clean_line%%[![:space:]]*}"}" # Trim leading spaces

            echo "$i. $clean_line" >>"$tmp_file"
            ((i++))
        done
        echo "$i. $id_or_task" >>"$tmp_file"
        echo "Adding: $id_or_task"
        ;;
    remove)
        i=1
        for line in "${lines[@]}"; do
            if [[ "${line%%.*}" != "${id_or_task}" ]]; then
                # Remove everything before the first dot and the dot itself
                clean_line="${line#*.}"
                clean_line="${clean_line#"${clean_line%%[![:space:]]*}"}" # Trim leading spaces
                echo "$i. $clean_line" >>"$tmp_file"
                ((i++))
            fi
        done
        echo "Removing task #: $id"
        ;;
    esac

}

show() {
    mapfile -t lines <"$file"

    for line in "${lines[@]}"; do
        echo "$line"
    done
}
add() {
    local task
    printf "task => "
    read -r task
    if [[ -n "$task" && "${task,,}" != "none" ]]; then
        rewrite_lines "$task"
        mv "$tmp_file" "$file"
        show
    else
        echo "[WARNING] There no any task."
    fi
}
remove() {
    local id
    printf "id => "
    read -r id
    if [[ "$id" =~ ^-?[0-9]+$ ]]; then
        rewrite_lines "$id"
        mv "$tmp_file" "$file"
        show
    else
        echo "[WARNING] Please write a correct task id."
    fi
}

case "$user_command" in
show) show ;;
add) add ;;
remove) remove ;;
esac
