test:
	go test ./internal/hasher/
	go test ./internal/repositorie/json/
	go test ./internal/url/
	go test ./cmd/

test-v:
	go test -v ./internal/hasher/
	go test -v ./internal/repositorie/json/
	go test -v ./internal/url/
	go test -v ./cmd/
