#!/usr/bin/env bash

if [ ! -d "$1" ]; then # check whether input targer_dir is actually DIR
    echo "Usage: $0 <path_to_directory>"
    exit 1
fi

target_dir=$(realpath "$1") # assign a full path to the input dir

echo "Start to undo last changes $target_dir dir."

for folder in "${target_dir}"/*; do # iterate all files in the targer_dir
    if [ -d "$folder" ]; then       # check whether it DIR or not
        echo "Moving files from $folder"
        mv "$folder"/* "$target_dir" # move all file from dir to the targer_dir
        echo "Remove empty folder $folder"
        rmdir "$folder" # remove empty dir
    fi
done
echo "Done."
