test:
	go test ./internal/infrastructure/databases/json/
	go test ./internal/domain/url/
	go test ./internal/infrastructure/hasher/
	go test ./internal/application/url/
	go test ./internal/transport/http/

test-v:
	go test -v ./internal/infrastructure/databases/json/
	go test -v ./internal/domain/url/
	go test -v ./internal/infrastructure/hasher/
	go test -v ./internal/application/url/
	go test -v ./internal/transport/http/
